### ISSUE TITLE
As a reminder, we are meeting tomorrow, 03-04-2016 at 2:00pm in CS Lab to get started!

### ISSUE THREAD

**Issue by ozyx** [SaddlebackCSS/AutonomousCar#1]
FUN!

**Comment by JoshGatmaitan** [comment]
I won't be able to make it today, something's just come up, I'm definitely still interested in the project and will be able to make any meetings in the future though!

**Comment by CrustyAuklet** [comment]
@JoshGatmaitan (and anyone else who can't make meetings). we will be setting up all the agile and teamwork tools today, so you should be able to follow along on those.
