### ISSUE TITLE
Main computer needs a stable and ready to program operating system

### ISSUE THREAD

**Issue by CrustyAuklet** [SaddlebackCSS/AutonomousCar#14]
Install Arch or Debian on the Beagle bone and make sure we know how to interface with the GPIO pins through C++.
- [ ] Install an OS on the computer
- [ ] Get development environment set up and whatever is needed to interface with GPIO

Needed for #2 

---
### Definition of done:

Main computer can read signals coming from another device or control an external device over GPIO using C++.

**Comment by dragon0** [comment]
You might also want to consider [The Robot Operating System](http://www.ros.org/) ([Wikipedia](https://en.wikipedia.org/wiki/Robot_Operating_System)).
